Add libsodium Public-key Signature Functionality
andrewhamon/cox pull request #2
Opened 2018-02-12 07:24 UTC by dorkrawk

Added libsodium bindings for Public-key Signatures: https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html

I needed this functionality for a project I'm working on and I thought it might be a nice expansion to this library.

Example usage:
```
message = "Hello World!"

signing_pair = Cox::SignKeyPair.new

# Sign the message
signature = Cox.sign(message, signing_pair.secret)

# And verify
Cox.verify(signature, message, signing_pair.public) # => true
```

2018-02-13 23:58 UTC, andrewhamon commented
Hey, somehow missed this until now! Taking a look now.

2018-02-14 00:22 UTC, andrewhamon requested changes
Thanks for the PR! Almost perfect just a few quibbles.

2018-02-14 00:22 UTC, andrewhamon commented on src/cox/signature.cr
> +  class Signature
I don't think this is being used at all is it? Can we delete it?

2018-02-14 00:22 UTC, andrewhamon commented on src/cox.cr
> +  def self.sign(message, secret_key : SignSecretKey)
Could we rename these to `sign_detached` and `verify_detached`? That leaves room to non-disruptively add the combined version down the road :)

2018-02-14 04:24 UTC, dorkrawk commented
Yep, I think those changes make total sense.  I've removed the `Signature` class and updated the method names.

2018-02-16 21:14 UTC, andrewhamon approved these changes
Thanks for the PR! Merging :D 

Sorry for the delay.

2018-02-16 21:14 UTC, merged